// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package naudotojai

import (
	"time"
)

type Gamintoja struct {
	ID          int64
	Pavadinimas string
	KilmesSalis string
}

type Parduotuve struct {
	ID          int64
	Pavadinimas string
	Nuotrauka   string
}

type Produkta struct {
	ID                    int64
	BruksninisKodas       string
	Pavadinimas           string
	Kaina                 string
	Kategorija            string
	Sudetis               string
	Maistingumas          string
	PagaminimoData        time.Time
	GaliojimoPabaigosData time.Time
	FkParduotuveID        int64
	FkGamintojasID        int64
}
