// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package naudotojai

import (
	"context"
)

const getShops = `-- name: GetShops :many
SELECT id, pavadinimas, nuotrauka FROM parduotuve
`

func (q *Queries) GetShops(ctx context.Context) ([]Parduotuve, error) {
	rows, err := q.db.QueryContext(ctx, getShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parduotuve
	for rows.Next() {
		var i Parduotuve
		if err := rows.Scan(&i.ID, &i.Pavadinimas, &i.Nuotrauka); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
